# Use a recent Miniconda image
FROM continuumio/miniconda3:latest

# Set environment variables
ENV PYTHONUNBUFFERED=1
SHELL ["/bin/bash", "-c"]

# Set the working directory in the container
WORKDIR /app

# Copy the environment.yml file into the container
COPY environment.yml .

# Update conda
RUN conda update -n base -c defaults conda --yes

# Create the Conda environment with specified packages
RUN conda env create -f environment.yml --verbose

# Initialize conda for bash
RUN conda init bash

# Ensure the environment is activated
RUN echo "source ~/.bashrc && conda activate opencvlab" >> ~/.bashrc

# Debugging step: Check if the environment is created
RUN bash -c "source ~/.bashrc && conda activate opencvlab && conda info --envs && conda list"

# Copy the rest of the working directory contents into the container
COPY . .

# Expose the port for Jupyter Notebook
EXPOSE 8888

# Command to run Jupyter Notebook
CMD ["bash", "-c", "source ~/.bashrc && conda activate opencvlab && jupyter notebook --ip=0.0.0.0 --allow-root"]
